/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBreadcrumb: typeof import('unuse-ui')['UBreadcrumb']
    UButton: typeof import('unuse-ui')['UButton']
    UCard: typeof import('unuse-ui')['UCard']
    UCheckbox: typeof import('unuse-ui')['UCheckbox']
    UContainer: typeof import('unuse-ui')['UContainer']
    UDialog: typeof import('unuse-ui')['UDialog']
    UDropdown: typeof import('unuse-ui')['UDropdown']
    UFormGroup: typeof import('unuse-ui')['UFormGroup']
    UIinput: typeof import('unuse-ui')['UIinput']
    UInput: typeof import('unuse-ui')['UInput']
    UModal: typeof import('unuse-ui')['UModal']
    UNav: typeof import('unuse-ui')['UNav']
    UPagination: typeof import('unuse-ui')['UPagination']
    UPopover: typeof import('unuse-ui')['UPopover']
    URadio: typeof import('unuse-ui')['URadio']
    USelect: typeof import('unuse-ui')['USelect']
    USelectMenu: typeof import('unuse-ui')['USelectMenu']
    USkeleton: typeof import('unuse-ui')['USkeleton']
    USlideover: typeof import('unuse-ui')['USlideover']
    USlider: typeof import('unuse-ui')['USlider']
    UTable: typeof import('unuse-ui')['UTable']
    UTag: typeof import('unuse-ui')['UTag']
    UTextarea: typeof import('unuse-ui')['UTextarea']
    UToggle: typeof import('unuse-ui')['UToggle']
    UTooltip: typeof import('unuse-ui')['UTooltip']
  }
}
