/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('unuse-ui')['UButton']
    UCheckbox: typeof import('unuse-ui')['UCheckbox']
    UFormGroup: typeof import('unuse-ui')['UFormGroup']
    UIinput: typeof import('unuse-ui')['UIinput']
    UInput: typeof import('unuse-ui')['UInput']
    UToggle: typeof import('unuse-ui')['UToggle']
  }
}
