export const selectMenu = {
  wrapper: 'relative',
  container: 'z-20',
  width: 'w-full',
  height: 'max-h-60',
  base: 'relative focus:outline-none overflow-y-auto scroll-py-1',
  background: 'bg-white dark:bg-dark-500',
  divide: '',
  shadow: 'shadow-lg',
  rounded: 'rounded-md',
  padding: 'p-1',
  ring: 'ring-1 ring-dark-100 dark:ring-dark-400',
  input: 'block w-[calc(100%+0.5rem)] focus:ring-transparent text-sm px-3 py-1.5 text-dark-400 dark:text-dark-100 bg-white dark:bg-dark-500 border-0 border-b border-dark-100 dark:border-dark-400 focus:border-inherit sticky -top-1 -mt-1 mb-1 -mx-1 z-10 placeholder-dark-200 dark:placeholder-dark-300',
  option: {
    base: 'cursor-default select-none relative flex items-center justify-between gap-1',
    rounded: 'rounded-md',
    padding: 'px-2 py-1.5',
    size: 'text-sm',
    color: 'text-dark-600 dark:text-white',
    container: 'flex items-center gap-2 min-w-0',
    active: 'bg-dark-50 dark:bg-dark-600',
    inactive: '',
    selected: 'pr-7',
    disabled: 'cursor-not-allowed opacity-50',
    empty: 'text-sm text-dark-200 dark:text-dark-300 px-2 py-1.5',
    icon: {
      base: 'flex-shrink-0 h-4 w-4',
      active: 'text-dark-600 dark:text-white',
      inactive: 'text-dark-200 dark:text-dark-300',
    },
    selectedIcon: {
      wrapper: 'absolute inset-y-0 right-0 flex items-center',
      padding: 'pr-2',
      base: 'h-4 w-4 text-dark-600 dark:text-white flex-shrink-0',
    },
    avatar: {
      base: 'flex-shrink-0',
      size: '3xs',
    },
    chip: {
      base: 'flex-shrink-0 w-2 h-2 mx-1 rounded-full',
    },
  },
  placeholder: '',
  transition: {
    leaveActiveClass: 'transition ease-in duration-100',
    leaveFromClass: 'opacity-100',
    leaveToClass: 'opacity-0',
  },
  popper: {
    placement: 'bottom-end',
  },
  default: {
    selectedIcon: 'i-ph-check-bold',
  },
}
