/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBreadcrumb: typeof import('./components/breadcrumb/UBreadcrumb.vue')['default']
    UButton: typeof import('./components/button/UButton.vue')['default']
    UCheckbox: typeof import('./components/checkbox/UCheckbox.vue')['default']
    UFormGroup: typeof import('./components/form-group/UFormGroup.vue')['default']
    UIcon: typeof import('./components/icon/UIcon.vue')['default']
    UInput: typeof import('./components/input/UInput.vue')['default']
    UNav: typeof import('./components/nav/UNav.vue')['default']
    UToggle: typeof import('./components/toggle/UToggle.vue')['default']
  }
}
