/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAvatar: typeof import('./components/avatar/UAvatar.vue')['default']
    UBreadcrumb: typeof import('./components/breadcrumb/UBreadcrumb.vue')['default']
    UButton: typeof import('./components/button/UButton.vue')['default']
    UCheckbox: typeof import('./components/checkbox/UCheckbox.vue')['default']
    UDialog: typeof import('./components/dialog/UDialog.vue')['default']
    UDropdown: typeof import('./components/dropdown/UDropdown.vue')['default']
    UFormGroup: typeof import('./components/form-group/UFormGroup.vue')['default']
    UIcon: typeof import('./components/icon/UIcon.vue')['default']
    UInput: typeof import('./components/input/UInput.vue')['default']
    UKbd: typeof import('./components/kbd/UKbd.vue')['default']
    ULinkCustom: typeof import('./components/link/ULinkCustom.vue')['default']
    UNav: typeof import('./components/nav/UNav.vue')['default']
    UPagination: typeof import('./components/pagination/UPagination.vue')['default']
    USelect: typeof import('./components/select/USelect.vue')['default']
    USelectMenu: typeof import('./components/select/USelectMenu.vue')['default']
    USlider: typeof import('./components/slider/USlider.vue')['default']
    UTable: typeof import('./components/table/UTable.vue')['default']
    UTag: typeof import('./components/tag/UTag.vue')['default']
    UTextarea: typeof import('./components/textarea/UTextarea.vue')['default']
    UToggle: typeof import('./components/toggle/UToggle.vue')['default']
    UTooltip: typeof import('./components/tooltip/UTooltip.vue')['default']
  }
}
