/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAvatar: typeof import('./components/avatar/UAvatar.vue')['default']
    UBreadcrumb: typeof import('./components/breadcrumb/UBreadcrumb.vue')['default']
    UButton: typeof import('./components/button/UButton.vue')['default']
    UCard: typeof import('./components/card/UCard.vue')['default']
    UCheckbox: typeof import('./components/checkbox/UCheckbox.vue')['default']
    UCollapse: typeof import('./components/collapse/UCollapse.vue')['default']
    UContainer: typeof import('./components/container/UContainer.vue')['default']
    UDatepicker: typeof import('./components/datepicker/UDatepicker.vue')['default']
    UDialog: typeof import('./components/dialog/UDialog.vue')['default']
    UDropdown: typeof import('./components/dropdown/UDropdown.vue')['default']
    UFileUpload: typeof import('./components/file-upload/UFileUpload.vue')['default']
    UFormGroup: typeof import('./components/form-group/UFormGroup.vue')['default']
    UIcon: typeof import('./components/icon/UIcon.vue')['default']
    UInput: typeof import('./components/input/UInput.vue')['default']
    ULinkCustom: typeof import('./components/link/ULinkCustom.vue')['default']
    UNav: typeof import('./components/nav/UNav.vue')['default']
    UNotification: typeof import('./components/notification/UNotification.vue')['default']
    UNotifications: typeof import('./components/notification/UNotifications.vue')['default']
    UPagination: typeof import('./components/pagination/UPagination.vue')['default']
    UPopover: typeof import('./components/popover/UPopover.vue')['default']
    URadio: typeof import('./components/radio/URadio.vue')['default']
    URadioGroup: typeof import('./components/radio/URadioGroup.vue')['default']
    USelect: typeof import('./components/select/USelect.vue')['default']
    USelectMenu: typeof import('./components/select/USelectMenu.vue')['default']
    USkeleton: typeof import('./components/skeleton/USkeleton.vue')['default']
    USlider: typeof import('./components/slider/USlider.vue')['default']
    UTable: typeof import('./components/table/UTable.vue')['default']
    UTag: typeof import('./components/tag/UTag.vue')['default']
    UText: typeof import('./components/text/UText.vue')['default']
    UTextarea: typeof import('./components/textarea/UTextarea.vue')['default']
    UToggle: typeof import('./components/toggle/UToggle.vue')['default']
    UTooltip: typeof import('./components/tooltip/UTooltip.vue')['default']
    UVerticalNavigation: typeof import('./components/vertical-navigation/UVerticalNavigation.vue')['default']
  }
}
